const fs = require('fs');
const path = require('path');

function walk(dir) {
  let results = [];
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    file = path.join(dir, file);
    const stat = fs.statSync(file);
    if (stat && stat.isDirectory()) { 
      results = results.concat(walk(file));
    } else { 
      results.push(file);
    }
  });
  return results;
}

const files = walk('src');
files.forEach(f => {
  if (f.endsWith('.tsx') || f.endsWith('.ts')) {
    let content = fs.readFileSync(f, 'utf8');
    // Replace escaped backticks and dollar signs which might have been generated by subagents
    let newContent = content.replace(/\\`/g, '`').replace(/\\\$/g, '$');
    if (content !== newContent) {
      console.log('Fixed', f);
      fs.writeFileSync(f, newContent);
    }
  }
});
