/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated/rules'
import { Route as AuthenticatedMlEngineRouteImport } from './routes/_authenticated/ml-engine'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedLinksIdRouteImport } from './routes/_authenticated/links.$id'
import { Route as ApiV1LinksIndexRouteImport } from './routes/api/v1/links/index'
import { Route as ApiV1LinksCheckSlugRouteImport } from './routes/api/v1/links/check-slug'
import { Route as ApiV1LinksIdRouteImport } from './routes/api/v1/links/$id'
import { Route as ApiV1AuthSignupRouteImport } from './routes/api/v1/auth/signup'
import { Route as ApiV1AuthMeRouteImport } from './routes/api/v1/auth/me'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMlEngineRoute = AuthenticatedMlEngineRouteImport.update({
  id: '/ml-engine',
  path: '/ml-engine',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinksIdRoute = AuthenticatedLinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLinksRoute,
} as any)
const ApiV1LinksIndexRoute = ApiV1LinksIndexRouteImport.update({
  id: '/api/v1/links/',
  path: '/api/v1/links/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LinksCheckSlugRoute = ApiV1LinksCheckSlugRouteImport.update({
  id: '/api/v1/links/check-slug',
  path: '/api/v1/links/check-slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LinksIdRoute = ApiV1LinksIdRouteImport.update({
  id: '/api/v1/links/$id',
  path: '/api/v1/links/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSignupRoute = ApiV1AuthSignupRouteImport.update({
  id: '/api/v1/auth/signup',
  path: '/api/v1/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/links': typeof AuthenticatedLinksRouteWithChildren
  '/ml-engine': typeof AuthenticatedMlEngineRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/links/$id': typeof AuthenticatedLinksIdRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/signup': typeof ApiV1AuthSignupRoute
  '/api/v1/links/$id': typeof ApiV1LinksIdRoute
  '/api/v1/links/check-slug': typeof ApiV1LinksCheckSlugRoute
  '/api/v1/links/': typeof ApiV1LinksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/links': typeof AuthenticatedLinksRouteWithChildren
  '/ml-engine': typeof AuthenticatedMlEngineRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/links/$id': typeof AuthenticatedLinksIdRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/signup': typeof ApiV1AuthSignupRoute
  '/api/v1/links/$id': typeof ApiV1LinksIdRoute
  '/api/v1/links/check-slug': typeof ApiV1LinksCheckSlugRoute
  '/api/v1/links': typeof ApiV1LinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/links': typeof AuthenticatedLinksRouteWithChildren
  '/_authenticated/ml-engine': typeof AuthenticatedMlEngineRoute
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/links/$id': typeof AuthenticatedLinksIdRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/signup': typeof ApiV1AuthSignupRoute
  '/api/v1/links/$id': typeof ApiV1LinksIdRoute
  '/api/v1/links/check-slug': typeof ApiV1LinksCheckSlugRoute
  '/api/v1/links/': typeof ApiV1LinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/docs'
    | '/links'
    | '/ml-engine'
    | '/rules'
    | '/security'
    | '/settings'
    | '/links/$id'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/signup'
    | '/api/v1/links/$id'
    | '/api/v1/links/check-slug'
    | '/api/v1/links/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/docs'
    | '/links'
    | '/ml-engine'
    | '/rules'
    | '/security'
    | '/settings'
    | '/links/$id'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/signup'
    | '/api/v1/links/$id'
    | '/api/v1/links/check-slug'
    | '/api/v1/links'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/analytics'
    | '/_authenticated/audit-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/docs'
    | '/_authenticated/links'
    | '/_authenticated/ml-engine'
    | '/_authenticated/rules'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/links/$id'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/signup'
    | '/api/v1/links/$id'
    | '/api/v1/links/check-slug'
    | '/api/v1/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1AuthSignupRoute: typeof ApiV1AuthSignupRoute
  ApiV1LinksIdRoute: typeof ApiV1LinksIdRoute
  ApiV1LinksCheckSlugRoute: typeof ApiV1LinksCheckSlugRoute
  ApiV1LinksIndexRoute: typeof ApiV1LinksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ml-engine': {
      id: '/_authenticated/ml-engine'
      path: '/ml-engine'
      fullPath: '/ml-engine'
      preLoaderRoute: typeof AuthenticatedMlEngineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/links/$id': {
      id: '/_authenticated/links/$id'
      path: '/$id'
      fullPath: '/links/$id'
      preLoaderRoute: typeof AuthenticatedLinksIdRouteImport
      parentRoute: typeof AuthenticatedLinksRoute
    }
    '/api/v1/links/': {
      id: '/api/v1/links/'
      path: '/api/v1/links'
      fullPath: '/api/v1/links/'
      preLoaderRoute: typeof ApiV1LinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/links/check-slug': {
      id: '/api/v1/links/check-slug'
      path: '/api/v1/links/check-slug'
      fullPath: '/api/v1/links/check-slug'
      preLoaderRoute: typeof ApiV1LinksCheckSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/links/$id': {
      id: '/api/v1/links/$id'
      path: '/api/v1/links/$id'
      fullPath: '/api/v1/links/$id'
      preLoaderRoute: typeof ApiV1LinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/signup': {
      id: '/api/v1/auth/signup'
      path: '/api/v1/auth/signup'
      fullPath: '/api/v1/auth/signup'
      preLoaderRoute: typeof ApiV1AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLinksRouteChildren {
  AuthenticatedLinksIdRoute: typeof AuthenticatedLinksIdRoute
}

const AuthenticatedLinksRouteChildren: AuthenticatedLinksRouteChildren = {
  AuthenticatedLinksIdRoute: AuthenticatedLinksIdRoute,
}

const AuthenticatedLinksRouteWithChildren =
  AuthenticatedLinksRoute._addFileChildren(AuthenticatedLinksRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRouteWithChildren
  AuthenticatedMlEngineRoute: typeof AuthenticatedMlEngineRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRouteWithChildren,
  AuthenticatedMlEngineRoute: AuthenticatedMlEngineRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1AuthSignupRoute: ApiV1AuthSignupRoute,
  ApiV1LinksIdRoute: ApiV1LinksIdRoute,
  ApiV1LinksCheckSlugRoute: ApiV1LinksCheckSlugRoute,
  ApiV1LinksIndexRoute: ApiV1LinksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
